language: python
python:
  - "3.8"

services:
  - postgresql

before_install:
  - openssl aes-256-cbc -K $encrypted_1443f6b77812_key -iv $encrypted_1443f6b77812_iv
    -in providedh-key.enc -out providedh-key -d
  - chmod 600 providedh-key

install:
  - pip install -r requirements.txt
  - cp src/collaborative_platform/collaborative_platform/settings_for_tests.py src/collaborative_platform/collaborative_platform/settings.py


script: cd src/collaborative_platform && pytest

deploy:
  skip_cleanup: true
  provider: script
  script: ssh -o "StrictHostKeyChecking no" ubuntu@providedh-test.ehum.psnc.pl -i providedh-key "cd collaborative-platform && ./prod_upgrade"
  on:
    branch: develop