language: python
before_install:
  - openssl aes-256-cbc -K $encrypted_1443f6b77812_key -iv $encrypted_1443f6b77812_iv
    -in providedh-key.enc -out providedh-key -d
deploy:
  provider: script
  script: ssh ubuntu@providedh-test.ehum.psnc.pl -i providedh-key "cd collaborative-platform && ./prod_upgrade"
  on:
    branch: develop