language: python
python:
  - "3.8"

addons:
  postgresql: "11"
  apt:
    packages:
      - postgresql-11
      - postgresql-client-11
      - postgresql-11-postgis-2.5
      - postgresql-server-dev-11
      - binutils
      - libproj-dev
      - gdal-bin

before_install:
  - openssl aes-256-cbc -K $encrypted_1443f6b77812_key -iv $encrypted_1443f6b77812_iv
    -in providedh-key.enc -out providedh-key -d
  - chmod 600 providedh-key

install:
  - pip install -r requirements.txt
  - cp src/collaborative_platform/collaborative_platform/settings.py_template src/collaborative_platform/collaborative_platform/settings.py

before_script:
  - psql -c "create database ctest;" -U postgres
  - psql -c "create user ctest with encrypted password 'ctest';" -U postgres
  - psql -c "grant all privileges on ctest to ctest;" -U postgres

script: cd src/collaborative_platform && pytest

deploy:
  skip_cleanup: true
  provider: script
  script: ssh -o "StrictHostKeyChecking no" ubuntu@providedh-test.ehum.psnc.pl -i providedh-key "cd collaborative-platform && ./prod_upgrade"
  on:
    branch: develop