language: python
python:
  - "3.8"
before_install:
  - openssl aes-256-cbc -K $encrypted_1443f6b77812_key -iv $encrypted_1443f6b77812_iv
    -in providedh-key.enc -out providedh-key -d
install:
  - pip install -r requirements.txt

script: echo "We have no tests :("

deploy:
  skip_cleanup: true
  provider: script
  script: ssh ubuntu@providedh-test.ehum.psnc.pl -i providedh-key "cd collaborative-platform && ./prod_upgrade"
  on:
    branch: develop